//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crianca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crianca()
        {
            this.Pagamentos = new HashSet<Pagamento>();
            this.Responsavels = new HashSet<Responsavel>();
        }
    
        public long Uid_crianca { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> Dt_nasc { get; set; }
        public Nullable<long> Uid_turma { get; set; }
        public string Sexo { get; set; }
        public Nullable<bool> Ativo { get; set; }

        public override string ToString()
        {
            return Nome;
        }

        public virtual Turma Turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responsavel> Responsavels { get; set; }
    }
}
